### ISSUE TITLE
是否还在更新

### ISSUE THREAD

**Issue by kelpiezqc** [xtherk/rust-jni-example#1]
这个库是否还在更新，在github上很难找到一个使用rust同时把jvmti和jni同时使用的很优雅的项目。另外 这个项目对Java版本的支持如何

**Comment by xtherk** [comment]
> 这个库是否还在更新，在github上很难找到一个使用rust同时把jvmti和jni同时使用的很优雅的项目。另外 这个项目对Java版本的支持如何

你好，感谢你的认可。 这个项目只是一个脚手架项目，内部集成好了jni和jvmti，无bug不会再更新了（也没什么可更新的，因为也没有什么功能）。

该项目依赖rust-jni，rust-jni项目一直保持活跃更新，若想支持新版java可以尝试更新rust-jni的版本号， jvmti则目前没有人维护，我已经将相关的函数更新至java17, 若需要更高版本的。例：jdk21，则可以去相应目录找到jvmti.h头文件自行更新。

**Comment by kelpiezqc** [comment]
respect
