### ISSUE TITLE
demo在mac arm上执行异常

### ISSUE THREAD

**Issue by kelpiezqc** [xtherk/rust-jni-example#2]
> java version "1.8.0_431"
Java(TM) SE Runtime Environment (build 1.8.0_431-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.431-b10, mixed mode)

运行main时日志为
>[2024-11-15T20:35:44.666] DEBUG Attached thread main (ThreadId(1)). 1 threads attached
[2024-11-15T20:35:44.670] DEBUG VM option: -Djava.library.path=.
[2024-11-15T20:35:44.670] DEBUG VM option: -XX:+DisableAttachMechanism
[2024-11-15T20:35:44.670] DEBUG VM option: -Dfile.encoding=UTF-8
[2024-11-15T20:35:44.670] DEBUG VM option: -Xms128M
[2024-11-15T20:35:44.670] DEBUG VM option: -Xmx128M
[2024-11-15T20:35:44.670] DEBUG Runtime vm param check pass!
进程已结束，退出代码为 139 (interrupted by signal 11:SIGSEGV)

定位原因为
https://github.com/xtherk/rust-jni-example/blob/master/src/main.rs#L106
此处没有真正取到jvmti，而L108这里没能check出来，最终在L110崩溃

**Comment by kelpiezqc** [comment]
我是arm的环境，也许与你的开发环境有些差异

**Comment by xtherk** [comment]
> 我是arm的环境，也许与你的开发环境有些差异

不好意思，我没mac，不然能查一下问题。我是在windows x64环境下开发的

**Comment by kelpiezqc** [comment]
找了一台ubuntu x64的设备运行也有一样的现象，不确定是不是需要额外的配置，我clone项目后只修改了config.ini的java_home配置

**Comment by kelpiezqc** [comment]
这个问题确认了是java版本的差异，我本地是8，你使用的应该是更新的版本，解决了这个问题后又出现了新的问题，这可能是当前没有一个主流的jvmti的rust库的原因，感谢

**Comment by xtherk** [comment]
> 这个问题确认了是java版本的差异，我本地是8，你使用的应该是更新的版本，解决了这个问题后又出现了新的问题，这可能是当前没有一个主流的jvmti的rust库的原因，感谢

我使用java17，如果你用windows，将java_home配置为17的目录应该是没有问题的。
最近项目较忙回复较慢，抱歉。
